apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: repo-yaml-deploy
spec:
  # 3 Pods should exist at all times.
  replicas: 3
  selector:
    matchLabels:
      app: codemine
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: codemine
    spec:
      containers:
      - name: nginx
        # Run this image
        image: nginx
